server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:file:D:/tmp/auth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true